import 'package:Pourosova/models/request/holding_entry_request.dart';
import 'package:flutter/material.dart';

class HoldingEntryProvider extends ChangeNotifier {
  HoldingEntryRequest _holdingEntryRequest = HoldingEntryRequest();

  HoldingEntryRequest get holdingEntryRequest => _holdingEntryRequest;

  void updateHoldingEntryRequest({
    String? holdingType,
    bool? isNewHolding,
    String? name,
    String? guardianType,
    String? guardianName,
    String? guardianMotherName,
    String? gender,
    String? maritalStatus,
    String? dateOfBirth,
    String? identityType,
    String? identityNumber,
    String? mobile,
    String? religion,
    String? familyType,
    String? familyMemberMale,
    String? familyMemberFemale,
    String? registrationFee,
    String? paymentType,
    String? allowance,
    String? allowanceDescription,
    String? disabilityStatus,
    String? freedomFighterStatus,
    String? waterConnectivityStatus,
    int? numberOfBirthCertificate,
    String? annualTax,
    bool? isGovernmentHolding,
    String? govtOfficeName,
    String? govtOfficerName,
    String? govtOfficerMobileNo,
    String? govtOfficeLength,
    String? govtOfficeWidth,
    String? holdingNo,
    String? wardNo,
    String? village,
    String? postCode,
    String? postOffice,
    String? electricityState,
    String? sanitationState,
    String? houseType,
    String? totalRoom,
    String? length,
    String? width,
    String? occupation,
    String? fiscalYear,
  }) {
    _holdingEntryRequest = _holdingEntryRequest!.copyWith(
      holdingType: holdingType,
      isNewHolding: isNewHolding,
      name: name,
      guardianType: guardianType,
      guardianName: guardianName,
      guardianMotherName: guardianMotherName,
      gender: gender,
      maritalStatus: maritalStatus,
      dateOfBirth: dateOfBirth,
      identityType: identityType,
      identityNumber: identityNumber,
      mobile: mobile,
      religion: religion,
      familyType: familyType,
      familyMemberMale: familyMemberMale,
      familyMemberFemale: familyMemberFemale,
      registrationFee: registrationFee,
      paymentType: paymentType,
      allowance: allowance,
      allowanceDescription: allowanceDescription,
      disabilityStatus: disabilityStatus,
      freedomFighterStatus: freedomFighterStatus,
      waterConnectivityStatus: waterConnectivityStatus,
      numberOfBirthCertificate: numberOfBirthCertificate,
      annualTax: annualTax,
      isGovernmentHolding: isGovernmentHolding,
      govtOfficeName: govtOfficeName,
      govtOfficerName: govtOfficerName,
      govtOfficerMobileNo: govtOfficerMobileNo,
      govtOfficeLength: govtOfficeLength,
      govtOfficeWidth: govtOfficeWidth,
      holdingNo: holdingNo,
      wardNo: wardNo,
      village: village,
      postCode: postCode,
      postOffice: postOffice,
      electricityState: electricityState,
      sanitationState: sanitationState,
      houseType: houseType,
      totalRoom: totalRoom,
      length: length,
      width: width,
      occupation: occupation,
      fiscalYear: fiscalYear,
    );
    notifyListeners();
  }
}
